import { css } from '@emotion/core';
import { Button, Card, Col, Progress, Row, Spin } from 'antd';
import React, { useCallback, useEffect, useState } from 'react';
import { useSelector } from 'react-redux';
import { useHistory } from 'react-router-dom';
import { useIntl } from 'react-intl';
import { Icon } from '@/components';
import { api } from '@/apis';
import { APISystemStatus } from '@/apis/siteSetting';
import { AppState } from '@/store';
import { FC } from '@/interfaces';
import { toLowerCamelCase } from '@/utils';
import style from '@/style';

interface SummaryValue<T = number> { value?: T; error?: boolean; }
interface AdminSummary { teams: SummaryValue; projects: SummaryValue; images: SummaryValue; storage: SummaryValue<{ total: number; used: number; free: number }>; system: SummaryValue<APISystemStatus>; }
const emptySummary = (): AdminSummary => ({ teams: {}, projects: {}, images: {}, storage: {}, system: {} });
const formatBytes = (bytes?: number | null) => { if (bytes == null || bytes < 0) return '—'; if (!bytes) return '0 B'; const units = ['B','KB','MB','GB','TB']; const i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / Math.pow(1024, i)).toFixed(1)} ${units[i]}`; };
const percentText = (value?: number | null) => value == null ? '—' : `${value.toFixed(1)}%`;
const SummaryCard: FC<{ title: string; icon: string; value: React.ReactNode; detail?: React.ReactNode; onClick: () => void }> = ({ title, icon, value, detail, onClick }) => <Card hoverable onClick={onClick} className="AdminDashboard__SummaryCard"><div className="AdminDashboard__CardIcon"><Icon icon={icon as any} /></div><div className="AdminDashboard__CardTitle">{title}</div><div className="AdminDashboard__CardValue">{value}</div>{detail && <div className="AdminDashboard__CardDetail">{detail}</div>}</Card>;

/** 管理员工作台首页：展示真实资源摘要与服务器状态 */
export const AdminDashboard: FC = () => {
  const { formatMessage } = useIntl(); const history = useHistory(); const user = useSelector((state: AppState) => state.user);
  const [summary, setSummary] = useState<AdminSummary>(emptySummary()); const [loading, setLoading] = useState(true);
  const loadSummary = useCallback(async () => { setLoading(true); const next = emptySummary(); const safe = (promise: Promise<any>, onSuccess: (result: any) => any, key: keyof AdminSummary) => promise.then((result) => { next[key] = { value: onSuccess(result) } as any; }).catch(() => { next[key] = { error: true }; }); await Promise.all([
    safe(api.adminTeam.listTeams({}), (result) => { const teams = ((result.data as any[]) || []).map((item) => toLowerCamelCase<any>(item)); next.teams = { value: teams.length }; next.images = { value: teams.reduce((n, item) => n + (item.imageCount || 0), 0) }; return teams.reduce((n, item) => n + (item.projectCount || 0), 0); }, 'projects'),
    safe(api.siteSetting.getStorageUsage({}), (result) => toLowerCamelCase(result.data), 'storage'),
    safe(api.siteSetting.getSystemStatus({}), (result) => toLowerCamelCase(result.data), 'system'),
  ]); setSummary(next); setLoading(false); }, []);
  useEffect(() => { loadSummary(); }, [loadSummary]);
  const unavailable = (item: SummaryValue) => item.error || item.value === undefined; const open = (path: string) => history.push(path); const storage = summary.storage.value; const system = summary.system.value; const storagePercent = storage && storage.total > 0 ? Math.min(100, Math.round(storage.used / storage.total * 100)) : undefined;
  const managementItems = [['admin.users','user-check','/admin/users'],['admin.imageModeration','image','/admin/image-moderation'],['admin.inviteCodes','link','/admin/invite-codes'],['admin.teamManage','layer-group','/admin/team-manage'],['admin.siteSettings','cog','/admin/site-setting']];
  return <div className="AdminDashboard" css={css`
    .AdminDashboard__Welcome{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:28px}.AdminDashboard__Eyebrow{color:${style.textColorSecondary};font-size:13px}.AdminDashboard__Heading{margin:6px 0 0;color:${style.textColor};font-size:34px;font-weight:500;letter-spacing:-1px}.AdminDashboard__Subheading{margin-top:8px;color:${style.textColorSecondary};font-size:14px}.AdminDashboard__SummaryRow{margin-bottom:24px}.AdminDashboard__SummaryCard{height:100%;border-radius:12px;border-color:${style.borderColorLight};box-shadow:none}.AdminDashboard__SummaryCard .ant-card-body{position:relative;padding:20px}.AdminDashboard__CardIcon{color:var(--moeflow-adminNavActive);font-size:18px}.AdminDashboard__CardTitle{margin-top:16px;color:${style.textColorSecondary};font-size:13px}.AdminDashboard__CardValue{margin-top:7px;color:${style.textColor};font-size:28px;font-weight:600}.AdminDashboard__CardDetail{margin-top:7px;color:${style.textColorSecondary};font-size:12px}.AdminDashboard__Grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr);gap:24px}.AdminDashboard__Panel{height:100%;border-radius:12px;border:1px solid ${style.borderColorLight};background:var(--moeflow-surface)}.AdminDashboard__PanelHeader{display:flex;align-items:center;justify-content:space-between;padding:20px 24px;border-bottom:1px solid ${style.borderColorLight}}.AdminDashboard__PanelTitle{color:${style.textColor};font-size:18px;font-weight:600}.AdminDashboard__PanelBody{padding:8px 24px}.AdminDashboard__ManagementItem{display:flex;align-items:center;width:100%;padding:14px 16px;border:0;border-radius:8px;background:transparent;color:${style.textColor};text-align:left;cursor:pointer}.AdminDashboard__ManagementItem:hover{background:${style.hoverColor}}.AdminDashboard__ManagementIcon{width:32px;color:var(--moeflow-adminNavActive)}.AdminDashboard__ManagementLabel{flex:1;font-size:14px}.AdminDashboard__StatusRow{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:15px 0;border-bottom:1px solid ${style.borderColorLight};color:${style.textColorSecondary};font-size:13px}.AdminDashboard__StatusRow:last-child{border-bottom:0}.AdminDashboard__StatusValue{color:${style.textColor};font-weight:600;text-align:right}.AdminDashboard__StatusProgress{flex:1;min-width:80px}@media(max-width:900px){.AdminDashboard__Grid{grid-template-columns:1fr}}@media(max-width:600px){.AdminDashboard__Welcome{align-items:flex-start;flex-direction:column;gap:14px}.AdminDashboard__Heading{font-size:28px}}
  `}>
    <div className="AdminDashboard__Welcome"><div><div className="AdminDashboard__Eyebrow">{formatMessage({id:'admin.overview'})}</div><h1 className="AdminDashboard__Heading">{formatMessage({id:'admin.greeting'},{name:user.name||'Admin'})}</h1><div className="AdminDashboard__Subheading">{formatMessage({id:'admin.greetingDescription'})}</div></div><Button icon={<Icon icon="sync"/>} onClick={loadSummary} loading={loading}>{formatMessage({id:'admin.refresh'})}</Button></div>
    <Row gutter={[16,16]} className="AdminDashboard__SummaryRow"><Col xs={24} sm={12} lg={6}><SummaryCard title={formatMessage({id:'admin.teamsSummary'})} icon="layer-group" value={unavailable(summary.teams)?formatMessage({id:'admin.unavailable'}):summary.teams.value} onClick={()=>open('/admin/team-manage')}/></Col><Col xs={24} sm={12} lg={6}><SummaryCard title={formatMessage({id:'admin.projectsSummary'})} icon="th-large" value={unavailable(summary.projects)?formatMessage({id:'admin.unavailable'}):summary.projects.value} onClick={()=>open('/admin/team-manage')}/></Col><Col xs={24} sm={12} lg={6}><SummaryCard title={formatMessage({id:'admin.imagesSummary'})} icon="image" value={unavailable(summary.images)?formatMessage({id:'admin.unavailable'}):summary.images.value} onClick={()=>open('/admin/image-moderation')}/></Col><Col xs={24} sm={12} lg={6}><SummaryCard title={formatMessage({id:'admin.storageSummary'})} icon="cloud" value={storage?formatBytes(storage.free):formatMessage({id:'admin.unavailable'})} detail={storage?formatMessage({id:'admin.storageFree'},{space:formatBytes(storage.free)}):undefined} onClick={()=>open('/admin/site-setting')}/></Col></Row>
    <div className="AdminDashboard__Grid"><div className="AdminDashboard__Panel"><div className="AdminDashboard__PanelHeader"><span className="AdminDashboard__PanelTitle">{formatMessage({id:'admin.quickActions'})}</span></div><div className="AdminDashboard__PanelBody">{managementItems.map(([id,icon,path])=><button key={path} type="button" className="AdminDashboard__ManagementItem" onClick={()=>open(path)}><span className="AdminDashboard__ManagementIcon"><Icon icon={icon as any}/></span><span className="AdminDashboard__ManagementLabel">{formatMessage({id})}</span><Icon icon="angle-right"/></button>)}</div></div><div className="AdminDashboard__Panel"><div className="AdminDashboard__PanelHeader"><span className="AdminDashboard__PanelTitle">{formatMessage({id:'admin.systemStatus'})}</span></div><div className="AdminDashboard__PanelBody"><div className="AdminDashboard__StatusRow"><span>{formatMessage({id:'admin.cpuUsage'})}</span><span className="AdminDashboard__StatusValue">{system?percentText(system.cpuPercent):formatMessage({id:'admin.unavailable'})}</span></div><div className="AdminDashboard__StatusRow"><span>{formatMessage({id:'admin.memoryUsage'})}</span><span className="AdminDashboard__StatusValue">{system?percentText(system.memoryPercent):formatMessage({id:'admin.unavailable'})}</span></div><div className="AdminDashboard__StatusRow"><span>{formatMessage({id:'admin.diskUsage'})}</span>{system&&system.diskPercent!=null?<><Progress className="AdminDashboard__StatusProgress" percent={system.diskPercent} showInfo={false} strokeColor="var(--moeflow-adminNavActive)"/><span className="AdminDashboard__StatusValue">{percentText(system.diskPercent)}</span></>:<span className="AdminDashboard__StatusValue">{formatMessage({id:'admin.unavailable'})}</span>}</div><div className="AdminDashboard__StatusRow"><span>{formatMessage({id:'admin.systemVersion'})}</span><span className="AdminDashboard__StatusValue">{system&&system.systemVersion?system.systemVersion:formatMessage({id:'admin.unavailable'})}</span></div></div></div></div>{loading&&!summary.teams.value&&<Spin/>}
  </div>;
};
export default AdminDashboard;
